# Generated by Django 4.0 on 2026-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='test_innings',
            field=models.IntegerField(),
        ),
    ]
